config/routes.rb
# == Route Map
#
#                    Prefix Verb   URI Pattern                                                                              Controller#Action
#            bills_callback POST   /bills/callback(.:format)                                                                bills#callback
#           bills_thank_you GET    /bills/thank_you(.:format)                                                               bills#thank_you
#              bills_cancel GET    /bills/cancel(.:format)                                                                  bills#cancel
#              manage_bills GET    /manage/bills(.:format)                                                                  manage/bills#index
#                           POST   /manage/bills(.:format)                                                                  manage/bills#create
#           new_manage_bill GET    /manage/bills/new(.:format)                                                              manage/bills#new
#               manage_bill GET    /manage/bills/:id(.:format)                                                              manage/bills#show
#                           DELETE /manage/bills/:id(.:format)                                                              manage/bills#destroy
#        manage_collections GET    /manage/collections(.:format)                                                            manage/collections#index
#                           POST   /manage/collections(.:format)                                                            manage/collections#create
#     new_manage_collection GET    /manage/collections/new(.:format)                                                        manage/collections#new
#    edit_manage_collection GET    /manage/collections/:id/edit(.:format)                                                   manage/collections#edit
#         manage_collection GET    /manage/collections/:id(.:format)                                                        manage/collections#show
#                           PATCH  /manage/collections/:id(.:format)                                                        manage/collections#update
#                           PUT    /manage/collections/:id(.:format)                                                        manage/collections#update
#                           DELETE /manage/collections/:id(.:format)                                                        manage/collections#destroy
#  manage_fundraising_index GET    /manage/fundraising(.:format)                                                            manage/fundraising#index
#                           POST   /manage/fundraising(.:format)                                                            manage/fundraising#create
#    new_manage_fundraising GET    /manage/fundraising/new(.:format)                                                        manage/fundraising#new
#   edit_manage_fundraising GET    /manage/fundraising/:id/edit(.:format)                                                   manage/fundraising#edit
#        manage_fundraising GET    /manage/fundraising/:id(.:format)                                                        manage/fundraising#show
#                           PATCH  /manage/fundraising/:id(.:format)                                                        manage/fundraising#update
#                           PUT    /manage/fundraising/:id(.:format)                                                        manage/fundraising#update
#                           DELETE /manage/fundraising/:id(.:format)                                                        manage/fundraising#destroy
#              manage_users GET    /manage/users(.:format)                                                                  manage/users#index
#                           POST   /manage/users(.:format)                                                                  manage/users#create
#           new_manage_user GET    /manage/users/new(.:format)                                                              manage/users#new
#               manage_user GET    /manage/users/:id(.:format)                                                              manage/users#show
#                           DELETE /manage/users/:id(.:format)                                                              manage/users#destroy
#            manage_profile GET    /manage/profile(.:format)                                                                manage/user_profiles#show
#       manage_profile_edit GET    /manage/profile/edit(.:format)                                                           manage/user_profiles#edit
#                           PATCH  /manage/profile(.:format)                                                                manage/user_profiles#update
#     manage_dashboard_root GET    /manage(.:format)                                                                        manage/dashboard#index
#                      root GET    /                                                                                        home#index
#          new_user_session GET    /users/sign_in(.:format)                                                                 users/sessions#new
#              user_session POST   /users/sign_in(.:format)                                                                 users/sessions#create
#      destroy_user_session DELETE /users/sign_out(.:format)                                                                users/sessions#destroy
#         new_user_password GET    /users/password/new(.:format)                                                            users/passwords#new
#        edit_user_password GET    /users/password/edit(.:format)                                                           users/passwords#edit
#             user_password PATCH  /users/password(.:format)                                                                users/passwords#update
#                           PUT    /users/password(.:format)                                                                users/passwords#update
#                           POST   /users/password(.:format)                                                                users/passwords#create
#        rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
# rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#        rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
# update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#      rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do

  post 'bills/callback'
  get 'bills/thank_you'
  get 'bills/cancel'
  namespace :manage do
    resources 'bills', except: [:edit, :update]
    resources 'collections'
    resources 'fundraising'
    resources 'users', except: [:edit, :update]
    get '/profile' ,to: 'user_profiles#show'
    get '/profile/edit' ,to: 'user_profiles#edit'
    patch '/profile' ,to: 'user_profiles#update'
    get '/', to: 'dashboard#index', as: 'dashboard_root'
  end
  root to: "home#index"
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations'
  }
end

app/views/layouts/_footer.html.erb
<footer class="main-footer">
  <div class="footer-left">
    <div class="bullet"></div> Made by <a href="https://github.com/syafiqfaiz/admin_billplz/">Syafiq Faiz</a>
  </div>
  <div class="footer-right">
    2019
  </div>
</footer>

app/views/layouts/_head.html.erb
<meta charset="UTF-8">
<meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
<title>BillplzTeam</title>
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_nav.html.erb
<div class="navbar-bg"></div>
<nav class="navbar navbar-expand-lg main-navbar">
  <ul class="navbar-nav mr-auto">
    <li><a href="#" data-toggle="sidebar" class="nav-link nav-link-lg"><i class="fas fa-bars"></i></a></li>
  </ul>
  <ul class="navbar-nav navbar-right">
    <li class="dropdown"><a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
      <div class="d-sm-none d-lg-inline-block">Hi, <%= current_user.name.capitalize %></div></a>
      <div class="dropdown-menu dropdown-menu-right">
        <a href="<%= manage_profile_path %>" class="dropdown-item has-icon">
          <i class="far fa-user"></i> Profile
        </a>
        <div class="dropdown-divider"></div>
        <%= link_to(destroy_user_session_path, method: :delete, class: "dropdown-item has-icon text-danger") do %>
          <i class="fas fa-sign-out-alt"></i> Logout
        <% end %>
      </div>
    </li>
  </ul>
</nav>

app/views/layouts/_notification.html.erb
<% if notice %><span class="notice" data-notice="<%= notice %>"></span><% end %>
<% if alert %><span class="alert" data-alert="<%= alert %>"></span><% end %>

app/views/layouts/_public_footer.html.erb
<footer class="main-footer">
  <div class="footer-left">
    2018 <div class="bullet"></div> <a href="https://syafiqfaiz.com">Syafiq Faiz</a>
  </div>
  <div class="footer-right">
    <%= link_to("Login", new_user_session_path) %>
  </div>
</footer>

app/views/layouts/_public_nav.html.erb
<nav class="navbar navbar-expand-lg main-navbar">
  <a href="index.html" class="navbar-brand sidebar-gone-hide">BillplzTeam</a>
  <div class="navbar-nav">
    <a href="#" class="nav-link sidebar-gone-show" data-toggle="sidebar"><i class="fas fa-bars"></i></a>
  </div>
</nav>

app/views/layouts/_sidebar.html.erb
<div class="main-sidebar sidebar-style-2">
  <aside id="sidebar-wrapper">
    <div class="sidebar-brand">
      <a href="<%= manage_dashboard_root_path %>">BillplzTeam</a>
    </div>
    <div class="sidebar-brand sidebar-brand-sm">
      <a href="<%= manage_dashboard_root_path %>">BT</a>
    </div>
    <ul class="sidebar-menu">
      <li class=><a class="nav-link" href="<%= manage_dashboard_root_path %>"><i class="far fa-square"></i> <span>Home</span></a></li>
      <li class=><a class="nav-link" href="<%= manage_users_path %>"><i class="far fa-square"></i> <span>Users</span></a></li>

      <li class="menu-header">Billplz</li>
      <li class="dropdown">
        <a href="#" class="nav-link has-dropdown" data-toggle="dropdown"><i class="fas fa-columns"></i> <span>Billplz</span></a>
        <ul class="dropdown-menu">
          <li><a class="nav-link" href="<%= manage_collections_path %>">Collection List</a></li>
          <li><a class="nav-link" href="<%= new_manage_collection_path %>">Create Collection</a></li>
          <li><a class="nav-link" href="<%= manage_bills_path %>">Bill List</a></li>
        </ul>
      </li>

      <li class="menu-header">Fundraising</li>
      <li class="dropdown">
        <a href="#" class="nav-link has-dropdown" data-toggle="dropdown"><i class="fas fa-columns"></i> <span>Fundraising</span></a>
        <ul class="dropdown-menu">
          <li><a class="nav-link" href="<%= manage_fundraising_index_path %>">Campaign List</a></li>
          <li><a class="nav-link" href="<%= new_manage_fundraising_path %>">Create Campaign</a></li>
        </ul>
      </li>

      <li class="menu-header">Store</li>
      <li class="dropdown">
        <a href="#" class="nav-link has-dropdown" data-toggle="dropdown"><i class="fas fa-columns"></i> <span>Store</span></a>
        <ul class="dropdown-menu">
          <li><a class="nav-link" href="layout-default.html">Product List</a></li>
          <li><a class="nav-link" href="layout-default.html">Order List</a></li>
          <li><a class="nav-link" href="layout-default.html">Create Product</a></li>
        </ul>
      </li>

      <li class="menu-header">Event</li>
      <li class="dropdown">
        <a href="#" class="nav-link has-dropdown" data-toggle="dropdown"><i class="fas fa-columns"></i> <span>Event</span></a>
        <ul class="dropdown-menu">
          <li><a class="nav-link" href="layout-default.html">Event List</a></li>
          <li><a class="nav-link" href="layout-default.html">Create Event</a></li>
        </ul>
      </li>

      <li class="menu-header">Contacts</li>
      <li class=><a class="nav-link" href="<%= manage_dashboard_root_path %>"><i class="far fa-square"></i> <span>Contact List</span></a></li>
    </ul>
  </aside>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <%= render :partial => "/layouts/head" %>
</head>
  <body>
      <div id="app">
        <div class="main-wrapper main-wrapper-1">
          <%= render :partial => "/layouts/nav.html.erb" %>
          <%= render :partial => "/layouts/sidebar.html.erb" %>
          <%= render :partial => "/layouts/notification.html.erb" %>
          <div class="full_page">
            <%= yield %>
          </div>
          <%= render :partial => "/layouts/footer.html.erb" %>
        </div>
      </div>
  </body>
</html>

app/views/layouts/auth.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <%= render :partial => "/layouts/head" %>
</head>
  <body>
  <div id="app">
    <%= render :partial => "/layouts/notification" %>

    <%= yield %>
  </div>
</body>
</html>

app/views/layouts/public.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <%= render :partial => "/layouts/head" %>
</head>
<body class="layout-3">
  <div id="app">
    <%= render :partial => "/layouts/notification" %>
    <div class="main-wrapper container">
      <div class="navbar-bg"></div>
      <%= render :partial => "/layouts/public_nav" %>

      <%= yield %>
      <%= render :partial => "/layouts/public_footer" %>
    </div>
  </div>
</body>
</html>